-- -----------------------------------------------------
-- Relacionamentos:
-- 1 Loja - 1 Contato
-- 1 Loja - N carros
-- N pessoa - N carros
-- 1 Pessoa - 1 Contato
-- -----------------------------------------------------


-- MySQL Script generated by MySQL Workbench
-- Wed Oct 13 17:48:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbcar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbcar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbcar` DEFAULT CHARACTER SET utf8 ;
USE `dbcar` ;

-- -----------------------------------------------------
-- Table `dbcar`.`tb_contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcar`.`tb_contato` (
  `id` INT NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `telefone_secundario` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcar`.`tb_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcar`.`tb_person` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `tb_contato_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_person_tb_contato1_idx` (`tb_contato_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_person_tb_contato1`
    FOREIGN KEY (`tb_contato_id`)
    REFERENCES `dbcar`.`tb_contato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcar`.`tb_revendedora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcar`.`tb_revendedora` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `tb_contato_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_revendedora_tb_contato1_idx` (`tb_contato_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_revendedora_tb_contato1`
    FOREIGN KEY (`tb_contato_id`)
    REFERENCES `dbcar`.`tb_contato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcar`.`tb_carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcar`.`tb_carro` (
  `id` INT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `tb_revendedora_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_carro_tb_revendedora1_idx` (`tb_revendedora_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_carro_tb_revendedora1`
    FOREIGN KEY (`tb_revendedora_id`)
    REFERENCES `dbcar`.`tb_revendedora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcar`.`tb_person_has_tb_carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcar`.`tb_person_has_tb_carro` (
  `tb_person_id` INT NOT NULL,
  `tb_carro_id` INT NOT NULL,
  PRIMARY KEY (`tb_person_id`, `tb_carro_id`),
  INDEX `fk_tb_person_has_tb_carro_tb_carro1_idx` (`tb_carro_id` ASC) VISIBLE,
  INDEX `fk_tb_person_has_tb_carro_tb_person_idx` (`tb_person_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_person_has_tb_carro_tb_person`
    FOREIGN KEY (`tb_person_id`)
    REFERENCES `dbcar`.`tb_person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_person_has_tb_carro_tb_carro1`
    FOREIGN KEY (`tb_carro_id`)
    REFERENCES `dbcar`.`tb_carro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
