-- MySQL Script generated by MySQL Workbench
-- sex 24 set 2021 20:01:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_legal_copy1_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_legal_copy1_copy1` (
  `id` INT NOT NULL,
  `muito` VARCHAR(45) NULL,
  `interessante` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_legal_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_legal_copy1` (
  `id` INT NOT NULL,
  `muito` VARCHAR(45) NULL,
  `interessante` VARCHAR(45) NULL,
  `tb_legal_copy1_copy1_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_legal_copy1_copy1_id`),
  INDEX `fk_tb_legal_copy1_tb_legal_copy1_copy11_idx` (`tb_legal_copy1_copy1_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_legal_copy1_tb_legal_copy1_copy11`
    FOREIGN KEY (`tb_legal_copy1_copy1_id`)
    REFERENCES `mydb`.`tb_legal_copy1_copy1` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_legal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_legal` (
  `id` INT NOT NULL,
  `muito` VARCHAR(45) NULL,
  `interessante` VARCHAR(45) NULL,
  `tb_legal_copy1_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tb_legal_copy1_id`),
  INDEX `fk_tb_legal_tb_legal_copy1_idx` (`tb_legal_copy1_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_legal_tb_legal_copy1`
    FOREIGN KEY (`tb_legal_copy1_id`)
    REFERENCES `mydb`.`tb_legal_copy1` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
