-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION "user";

COMMENT ON SCHEMA public IS 'standard public schema';

-- DROP SEQUENCE public.tb_gate_id_seq;

CREATE SEQUENCE public.tb_gate_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_local_id_seq;

CREATE SEQUENCE public.tb_local_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_local_type_id_seq;

CREATE SEQUENCE public.tb_local_type_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_location_id_seq;

CREATE SEQUENCE public.tb_location_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_piece_id_seq;

CREATE SEQUENCE public.tb_piece_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_reader_id_seq;

CREATE SEQUENCE public.tb_reader_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_scope_id_seq;

CREATE SEQUENCE public.tb_scope_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_tag_id_seq;

CREATE SEQUENCE public.tb_tag_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_tag_type_id_seq;

CREATE SEQUENCE public.tb_tag_type_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_train_id_seq;

CREATE SEQUENCE public.tb_train_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_wagon_id_seq;

CREATE SEQUENCE public.tb_wagon_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_wagon_path_id_seq;

CREATE SEQUENCE public.tb_wagon_path_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tb_wagon_station_id_seq;

CREATE SEQUENCE public.tb_wagon_station_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public."__EFMigrationsHistory" definition

-- Drop table

-- DROP TABLE public."__EFMigrationsHistory";

CREATE TABLE public."__EFMigrationsHistory" (
	"MigrationId" varchar(150) NOT NULL,
	"ProductVersion" varchar(32) NOT NULL,
	CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);


-- public.tb_scope definition

-- Drop table

-- DROP TABLE public.tb_scope;

CREATE TABLE public.tb_scope (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	hash_sope text NULL,
	scope_id int8 NULL,
	"ScopeId1" int8 NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT "PK_tb_scope" PRIMARY KEY (id),
	CONSTRAINT "FK_tb_scope_tb_scope_ScopeId1" FOREIGN KEY ("ScopeId1") REFERENCES public.tb_scope(id) ON DELETE RESTRICT
);
CREATE INDEX "IX_tb_scope_ScopeId1" ON public.tb_scope USING btree ("ScopeId1");


-- public.tb_tag_type definition

-- Drop table

-- DROP TABLE public.tb_tag_type;

CREATE TABLE public.tb_tag_type (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Icon" text NULL,
	"Frequency" float4 NOT NULL,
	scope_id int8 NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	"Model" text NULL,
	"CustomName" text NULL,
	"Description" text NULL,
	"DimX" float4 NOT NULL,
	"DimY" float4 NOT NULL,
	"DimZ" float4 NOT NULL,
	"Media3D" text NULL,
	"Media" text NULL,
	CONSTRAINT "PK_tb_tag_type" PRIMARY KEY (id),
	CONSTRAINT "FK_tb_tag_type_tb_scope_scope_id" FOREIGN KEY (scope_id) REFERENCES public.tb_scope(id) ON DELETE RESTRICT
);
CREATE INDEX "IX_tb_tag_type_scope_id" ON public.tb_tag_type USING btree (scope_id);


-- public.tb_local_type definition

-- Drop table

-- DROP TABLE public.tb_local_type;

CREATE TABLE public.tb_local_type (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Name" text NULL,
	"Description" text NULL,
	"Icon" text NULL,
	"Media" text NULL,
	scope_id int8 NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT "PK_tb_local_type" PRIMARY KEY (id),
	CONSTRAINT "FK_tb_local_type_tb_scope_scope_id" FOREIGN KEY (scope_id) REFERENCES public.tb_scope(id) ON DELETE RESTRICT
);
CREATE INDEX "IX_tb_local_type_scope_id" ON public.tb_local_type USING btree (scope_id);


-- public.tb_location definition

-- Drop table

-- DROP TABLE public.tb_location;

CREATE TABLE public.tb_location (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Lat" text NULL,
	"Lon" text NULL,
	"Street" text NULL,
	"Neighborhood" text NULL,
	"City" text NULL,
	"Number" text NULL,
	scope_id int8 NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT "PK_tb_location" PRIMARY KEY (id),
	CONSTRAINT "FK_tb_location_tb_scope_scope_id" FOREIGN KEY (scope_id) REFERENCES public.tb_scope(id) ON DELETE RESTRICT
);
CREATE INDEX "IX_tb_location_scope_id" ON public.tb_location USING btree (scope_id);


-- public.tb_reader definition

-- Drop table

-- DROP TABLE public.tb_reader;

CREATE TABLE public.tb_reader (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Frequency" float4 NULL,
	"DistanceRange" float4 NULL,
	"ParableRange" float4 NULL,
	scope_id int8 NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	"Model" text NULL,
	"CustomName" text NULL,
	"Description" text NULL,
	"DimX" float4 NOT NULL,
	"DimY" float4 NOT NULL,
	"DimZ" float4 NOT NULL,
	"Media3D" text NULL,
	"Media" text NULL,
	CONSTRAINT "PK_tb_reader" PRIMARY KEY (id),
	CONSTRAINT "FK_tb_reader_tb_scope_scope_id" FOREIGN KEY (scope_id) REFERENCES public.tb_scope(id) ON DELETE RESTRICT
);
CREATE INDEX "IX_tb_reader_scope_id" ON public.tb_reader USING btree (scope_id);


-- public.tb_tag definition

-- Drop table

-- DROP TABLE public.tb_tag;

CREATE TABLE public.tb_tag (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Value" text NULL,
	"TagTypeId" int8 NOT NULL,
	scope_id int8 NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	"Model" text NULL,
	"CustomName" text NULL,
	"Description" text NULL,
	"DimX" float4 NOT NULL,
	"DimY" float4 NOT NULL,
	"DimZ" float4 NOT NULL,
	"Media3D" text NULL,
	"Media" text NULL,
	CONSTRAINT "PK_tb_tag" PRIMARY KEY (id),
	CONSTRAINT "FK_tb_tag_tb_scope_scope_id" FOREIGN KEY (scope_id) REFERENCES public.tb_scope(id) ON DELETE RESTRICT,
	CONSTRAINT "FK_tb_tag_tb_tag_type_TagTypeId" FOREIGN KEY ("TagTypeId") REFERENCES public.tb_tag_type(id) ON DELETE CASCADE
);
CREATE INDEX "IX_tb_tag_TagTypeId" ON public.tb_tag USING btree ("TagTypeId");
CREATE INDEX "IX_tb_tag_scope_id" ON public.tb_tag USING btree (scope_id);


-- public.tb_train definition

-- Drop table

-- DROP TABLE public.tb_train;

CREATE TABLE public.tb_train (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"TagId" int8 NOT NULL,
	scope_id int8 NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT "PK_tb_train" PRIMARY KEY (id),
	CONSTRAINT "FK_tb_train_tb_scope_scope_id" FOREIGN KEY (scope_id) REFERENCES public.tb_scope(id) ON DELETE RESTRICT,
	CONSTRAINT "FK_tb_train_tb_tag_TagId" FOREIGN KEY ("TagId") REFERENCES public.tb_tag(id) ON DELETE CASCADE
);
CREATE INDEX "IX_tb_train_TagId" ON public.tb_train USING btree ("TagId");
CREATE INDEX "IX_tb_train_scope_id" ON public.tb_train USING btree (scope_id);


-- public.tb_wagon definition

-- Drop table

-- DROP TABLE public.tb_wagon;

CREATE TABLE public.tb_wagon (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"TagId" int8 NOT NULL,
	scope_id int8 NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	"Model" text NULL,
	"CustomName" text NULL,
	"Description" text NULL,
	"DimX" float4 NOT NULL,
	"DimY" float4 NOT NULL,
	"DimZ" float4 NOT NULL,
	"Media3D" text NULL,
	"Media" text NULL,
	CONSTRAINT "PK_tb_wagon" PRIMARY KEY (id),
	CONSTRAINT "FK_tb_wagon_tb_scope_scope_id" FOREIGN KEY (scope_id) REFERENCES public.tb_scope(id) ON DELETE RESTRICT,
	CONSTRAINT "FK_tb_wagon_tb_tag_TagId" FOREIGN KEY ("TagId") REFERENCES public.tb_tag(id) ON DELETE CASCADE
);
CREATE INDEX "IX_tb_wagon_TagId" ON public.tb_wagon USING btree ("TagId");
CREATE INDEX "IX_tb_wagon_scope_id" ON public.tb_wagon USING btree (scope_id);


-- public.tb_local definition

-- Drop table

-- DROP TABLE public.tb_local;

CREATE TABLE public.tb_local (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"DimX" float4 NULL,
	"DimY" float4 NULL,
	"DimZ" float4 NULL,
	"Name" text NULL,
	"XStationsQtd" float4 NULL,
	"YStationsQtd" float4 NULL,
	"LocalTypeId" int8 NOT NULL,
	"LocationId" int8 NOT NULL,
	scope_id int8 NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT "PK_tb_local" PRIMARY KEY (id),
	CONSTRAINT "FK_tb_local_tb_local_type_LocalTypeId" FOREIGN KEY ("LocalTypeId") REFERENCES public.tb_local_type(id) ON DELETE CASCADE,
	CONSTRAINT "FK_tb_local_tb_location_LocationId" FOREIGN KEY ("LocationId") REFERENCES public.tb_location(id) ON DELETE CASCADE,
	CONSTRAINT "FK_tb_local_tb_scope_scope_id" FOREIGN KEY (scope_id) REFERENCES public.tb_scope(id) ON DELETE RESTRICT
);
CREATE INDEX "IX_tb_local_LocalTypeId" ON public.tb_local USING btree ("LocalTypeId");
CREATE INDEX "IX_tb_local_LocationId" ON public.tb_local USING btree ("LocationId");
CREATE INDEX "IX_tb_local_scope_id" ON public.tb_local USING btree (scope_id);


-- public.tb_piece definition

-- Drop table

-- DROP TABLE public.tb_piece;

CREATE TABLE public.tb_piece (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"TagId" int8 NOT NULL,
	scope_id int8 NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	"Model" text NULL,
	"CustomName" text NULL,
	"Description" text NULL,
	"DimX" float4 NOT NULL,
	"DimY" float4 NOT NULL,
	"DimZ" float4 NOT NULL,
	"Media3D" text NULL,
	"Media" text NULL,
	CONSTRAINT "PK_tb_piece" PRIMARY KEY (id),
	CONSTRAINT "FK_tb_piece_tb_scope_scope_id" FOREIGN KEY (scope_id) REFERENCES public.tb_scope(id) ON DELETE RESTRICT,
	CONSTRAINT "FK_tb_piece_tb_tag_TagId" FOREIGN KEY ("TagId") REFERENCES public.tb_tag(id) ON DELETE CASCADE
);
CREATE INDEX "IX_tb_piece_TagId" ON public.tb_piece USING btree ("TagId");
CREATE INDEX "IX_tb_piece_scope_id" ON public.tb_piece USING btree (scope_id);


-- public.tb_piece_path definition

-- Drop table

-- DROP TABLE public.tb_piece_path;

CREATE TABLE public.tb_piece_path (
	"PieceId" int8 NOT NULL,
	"LocalId" int8 NOT NULL,
	id int8 NOT NULL,
	register_date timestamp NULL,
	created_by int4 NULL,
	created_on timestamp NULL,
	scope_id int8 NULL,
	updated_by int4 NULL,
	updated_on timestamp NULL,
	CONSTRAINT "PK_tb_piece_path" PRIMARY KEY ("PieceId", "LocalId"),
	CONSTRAINT "FK_tb_piece_path_tb_local_LocalId" FOREIGN KEY ("LocalId") REFERENCES public.tb_local(id) ON DELETE CASCADE,
	CONSTRAINT "FK_tb_piece_path_tb_piece_PieceId" FOREIGN KEY ("PieceId") REFERENCES public.tb_piece(id) ON DELETE CASCADE,
	CONSTRAINT "FK_tb_piece_path_tb_scope_scope_id" FOREIGN KEY (scope_id) REFERENCES public.tb_scope(id) ON DELETE RESTRICT
);
CREATE INDEX "IX_tb_piece_path_LocalId" ON public.tb_piece_path USING btree ("LocalId");
CREATE INDEX "IX_tb_piece_path_scope_id" ON public.tb_piece_path USING btree (scope_id);


-- public.tb_train_path definition

-- Drop table

-- DROP TABLE public.tb_train_path;

CREATE TABLE public.tb_train_path (
	"TrainId" int8 NOT NULL,
	"LocalId" int8 NOT NULL,
	id int8 NOT NULL,
	register_date timestamp NULL,
	created_by int4 NULL,
	created_on timestamp NULL,
	scope_id int8 NULL,
	updated_by int4 NULL,
	updated_on timestamp NULL,
	CONSTRAINT "PK_tb_train_path" PRIMARY KEY ("TrainId", "LocalId"),
	CONSTRAINT "FK_tb_train_path_tb_local_LocalId" FOREIGN KEY ("LocalId") REFERENCES public.tb_local(id) ON DELETE CASCADE,
	CONSTRAINT "FK_tb_train_path_tb_scope_scope_id" FOREIGN KEY (scope_id) REFERENCES public.tb_scope(id) ON DELETE RESTRICT,
	CONSTRAINT "FK_tb_train_path_tb_train_TrainId" FOREIGN KEY ("TrainId") REFERENCES public.tb_train(id) ON DELETE CASCADE
);
CREATE INDEX "IX_tb_train_path_LocalId" ON public.tb_train_path USING btree ("LocalId");
CREATE INDEX "IX_tb_train_path_scope_id" ON public.tb_train_path USING btree (scope_id);


-- public.tb_wagon_path definition

-- Drop table

-- DROP TABLE public.tb_wagon_path;

CREATE TABLE public.tb_wagon_path (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	register_date timestamp NULL,
	"WagonId" int8 NOT NULL,
	"LocalId" int8 NOT NULL,
	created_by int4 NULL,
	created_on timestamp NULL,
	scope_id int8 NULL,
	updated_by int4 NULL,
	updated_on timestamp NULL,
	CONSTRAINT "PK_tb_wagon_path" PRIMARY KEY (id),
	CONSTRAINT "FK_tb_wagon_path_tb_local_LocalId" FOREIGN KEY ("LocalId") REFERENCES public.tb_local(id) ON DELETE CASCADE,
	CONSTRAINT "FK_tb_wagon_path_tb_scope_scope_id" FOREIGN KEY (scope_id) REFERENCES public.tb_scope(id) ON DELETE RESTRICT,
	CONSTRAINT "FK_tb_wagon_path_tb_wagon_WagonId" FOREIGN KEY ("WagonId") REFERENCES public.tb_wagon(id) ON DELETE CASCADE
);
CREATE INDEX "IX_tb_wagon_path_LocalId" ON public.tb_wagon_path USING btree ("LocalId");
CREATE INDEX "IX_tb_wagon_path_WagonId" ON public.tb_wagon_path USING btree ("WagonId");
CREATE INDEX "IX_tb_wagon_path_scope_id" ON public.tb_wagon_path USING btree (scope_id);


-- public.tb_wagon_piece definition

-- Drop table

-- DROP TABLE public.tb_wagon_piece;

CREATE TABLE public.tb_wagon_piece (
	"WagonId" int8 NOT NULL,
	"PieceId" int8 NOT NULL,
	"InstallationDate" timestamp NOT NULL,
	"DesinstallationDate" timestamp NOT NULL,
	"InstallLocationId" int8 NULL,
	"DesinstallLocationId" int8 NULL,
	id int8 NOT NULL,
	scope_id int8 NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT "PK_tb_wagon_piece" PRIMARY KEY ("WagonId", "PieceId"),
	CONSTRAINT "FK_tb_wagon_piece_tb_location_DesinstallLocationId" FOREIGN KEY ("DesinstallLocationId") REFERENCES public.tb_location(id) ON DELETE RESTRICT,
	CONSTRAINT "FK_tb_wagon_piece_tb_location_InstallLocationId" FOREIGN KEY ("InstallLocationId") REFERENCES public.tb_location(id) ON DELETE RESTRICT,
	CONSTRAINT "FK_tb_wagon_piece_tb_piece_PieceId" FOREIGN KEY ("PieceId") REFERENCES public.tb_piece(id) ON DELETE CASCADE,
	CONSTRAINT "FK_tb_wagon_piece_tb_scope_scope_id" FOREIGN KEY (scope_id) REFERENCES public.tb_scope(id) ON DELETE RESTRICT,
	CONSTRAINT "FK_tb_wagon_piece_tb_wagon_WagonId" FOREIGN KEY ("WagonId") REFERENCES public.tb_wagon(id) ON DELETE CASCADE
);
CREATE INDEX "IX_tb_wagon_piece_DesinstallLocationId" ON public.tb_wagon_piece USING btree ("DesinstallLocationId");
CREATE INDEX "IX_tb_wagon_piece_InstallLocationId" ON public.tb_wagon_piece USING btree ("InstallLocationId");
CREATE INDEX "IX_tb_wagon_piece_PieceId" ON public.tb_wagon_piece USING btree ("PieceId");
CREATE INDEX "IX_tb_wagon_piece_scope_id" ON public.tb_wagon_piece USING btree (scope_id);


-- public.tb_wagon_station definition

-- Drop table

-- DROP TABLE public.tb_wagon_station;

CREATE TABLE public.tb_wagon_station (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"LocalId" int8 NOT NULL,
	"positionX" int8 NOT NULL,
	"positionY" int8 NOT NULL,
	scope_id int8 NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT "PK_tb_wagon_station" PRIMARY KEY (id),
	CONSTRAINT "FK_tb_wagon_station_tb_local_LocalId" FOREIGN KEY ("LocalId") REFERENCES public.tb_local(id) ON DELETE CASCADE,
	CONSTRAINT "FK_tb_wagon_station_tb_scope_scope_id" FOREIGN KEY (scope_id) REFERENCES public.tb_scope(id) ON DELETE RESTRICT
);
CREATE INDEX "IX_tb_wagon_station_LocalId" ON public.tb_wagon_station USING btree ("LocalId");
CREATE INDEX "IX_tb_wagon_station_scope_id" ON public.tb_wagon_station USING btree (scope_id);


-- public.tb_gate definition

-- Drop table

-- DROP TABLE public.tb_gate;

CREATE TABLE public.tb_gate (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Description" text NULL,
	"Identifier" text NULL,
	"GateType" int4 NOT NULL,
	"LocalId" int8 NOT NULL,
	scope_id int8 NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	CONSTRAINT "PK_tb_gate" PRIMARY KEY (id),
	CONSTRAINT "FK_tb_gate_tb_local_LocalId" FOREIGN KEY ("LocalId") REFERENCES public.tb_local(id) ON DELETE CASCADE,
	CONSTRAINT "FK_tb_gate_tb_scope_scope_id" FOREIGN KEY (scope_id) REFERENCES public.tb_scope(id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX "IX_tb_gate_LocalId" ON public.tb_gate USING btree ("LocalId");
CREATE INDEX "IX_tb_gate_scope_id" ON public.tb_gate USING btree (scope_id);
